% One-liner function to calculate true anomaly from mean anomaly
mean_to_true_anomaly = @(M, e) arrayfun(@(M_rad) rad2deg(2 * atan(sqrt((1 + e) / (1 - e)) * tan((M_rad + e * sin(M_rad)) / 2))), deg2rad(M));

% Example usage
M = 30;  % Mean anomaly in degrees
e = 0.1; % Example eccentricity
true_anomaly_deg = mean_to_true_anomaly(M, e);

% Display result
fprintf('True Anomaly (degrees): %.4f\n', true_anomaly_deg);



    tleStruct = struct(...
        'Name', '', ...
        'SatelliteCatalogNumber', '', ...
        'Epoch', '', ...
        'BStar', '', ...
        'RightAscensionOfAscendingNode', [], ...
        'Eccentricity', [], ...
        'Inclination', [], ...
        'ArgumentOfPeriapsis', [], ...
        'MeanAnomaly', [], ...
        'MeanMotion', [] ...
    );


